# Generated by Django 4.0.4 on 2022-04-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jams_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
    ]
