# Generated by Django 4.0.4 on 2022-04-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams_library', '0003_album_artist_song_album_song_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='song_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='active_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='monthly_listeners',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='jams_library.genre'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(to='jams_library.genre'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(to='jams_library.genre'),
        ),
    ]
