# Generated by Django 4.0.4 on 2022-04-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jams_library', '0004_genre_album_duration_album_song_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='active_from',
        ),
    ]
