# Generated by Django 4.0.4 on 2022-04-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams_library', '0005_remove_artist_active_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='active_from',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
