# Generated by Django 4.0.4 on 2022-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams_library', '0006_artist_active_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='song',
            name='track',
            field=models.IntegerField(default=0),
        ),
    ]
