# Generated by Django 4.0.4 on 2022-04-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams_library', '0007_remove_song_duration_song_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
